version: '3'

services:
  example-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    ports:
      - 5000:5000
      - 9229:9229
    command: npm start